name: Docker
on:
    release:
        types:
        -  published
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v3
        -   name: Echo Release Version Number
            run: |
                echo "Release Version Number is ${{ github.event.release.tag_name }}"
        -   name: Echo Commit Number
            run: |
                echo ${{ github.sha }}
        -   name: Read SHA
            run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        -   name: Echo SHA
            run: |
                echo ${{ env.SHA }}